const wordPairs = [
  // --- INDIAN FOOD & DRINK (Desi Style) ---
  { civilian: "Biryani", undercover: "Pulao", category: "Food" },
  { civilian: "Chai", undercover: "Coffee", category: "Food" },
  { civilian: "Samosa", undercover: "Kachori", category: "Food" },
  { civilian: "Roti", undercover: "Naan", category: "Food" },
  { civilian: "Paratha", undercover: "Chapati", category: "Food" },
  { civilian: "Idli", undercover: "Dosa", category: "Food" },
  { civilian: "Paneer", undercover: "Tofu", category: "Food" },
  { civilian: "Dal", undercover: "Sambar", category: "Food" },
  { civilian: "Lassi", undercover: "Milkshake", category: "Food" },
  { civilian: "Gulab Jamun", undercover: "Rasgulla", category: "Food" },
  { civilian: "Jalebi", undercover: "Imarti", category: "Food" },
  { civilian: "Pani Puri", undercover: "Bhel Puri", category: "Food" },
  { civilian: "Vada Pav", undercover: "Burger", category: "Food" },
  { civilian: "Maggi", undercover: "Noodles", category: "Food" },
  { civilian: "Pickle", undercover: "Chutney", category: "Food" },
  { civilian: "Ghee", undercover: "Butter", category: "Food" },
  { civilian: "Curd", undercover: "Yogurt", category: "Food" },
  { civilian: "Rice", undercover: "Wheat", category: "Food" },
  { civilian: "Mango", undercover: "Banana", category: "Food" },
  { civilian: "Coconut", undercover: "Papaya", category: "Food" },
  { civilian: "Thali", undercover: "Buffet", category: "Food" },
  { civilian: "Kheer", undercover: "Halwa", category: "Food" },
  { civilian: "Omelette", undercover: "Boiled Egg", category: "Food" },
  { civilian: "Biscuit", undercover: "Rusk", category: "Food" },
  { civilian: "Pepsi", undercover: "Coke", category: "Food" },
  { civilian: "Sprite", undercover: "7Up", category: "Food" },
  { civilian: "Kurkure", undercover: "Lays", category: "Food" },
  { civilian: "Chocolate", undercover: "Candy", category: "Food" },
  { civilian: "Ice Cream", undercover: "Kulfi", category: "Food" },
  { civilian: "Soup", undercover: "Curry", category: "Food" },
  { civilian: "Salt", undercover: "Sugar", category: "Food" },
  { civilian: "Onion", undercover: "Garlic", category: "Food" },
  { civilian: "Potato", undercover: "Tomato", category: "Food" },
  { civilian: "Ginger", undercover: "Garlic", category: "Food" },
  { civilian: "Almond", undercover: "Cashew", category: "Food" },
  { civilian: "Peanut", undercover: "Walnut", category: "Food" },
  { civilian: "Chicken", undercover: "Mutton", category: "Food" },
  { civilian: "Fish", undercover: "Prawns", category: "Food" },
  { civilian: "Egg", undercover: "Chicken", category: "Food" },
  { civilian: "Water", undercover: "Soda", category: "Food" },
  { civilian: "Milk", undercover: "Curd", category: "Food" },
  { civilian: "Juice", undercover: "Squash", category: "Food" },
  { civilian: "Sandwich", undercover: "Toast", category: "Food" },
  { civilian: "Pizza", undercover: "Pasta", category: "Food" },
  { civilian: "Cake", undercover: "Pastry", category: "Food" },
  { civilian: "Sugar", undercover: "Jaggery (Gud)", category: "Food" },
  { civilian: "Lemon", undercover: "Orange", category: "Food" },
  { civilian: "Apple", undercover: "Guava", category: "Food" },
  { civilian: "Grape", undercover: "Berry", category: "Food" },
  { civilian: "Watermelon", undercover: "Melon", category: "Food" },

  // --- DAILY LIFE & HOME (Indian Context) ---
  { civilian: "Fan", undercover: "AC", category: "Home" },
  { civilian: "Bucket", undercover: "Mug", category: "Home" },
  { civilian: "Broom", undercover: "Mop", category: "Home" },
  { civilian: "Soap", undercover: "Shampoo", category: "Home" },
  { civilian: "Towel", undercover: "Handkerchief", category: "Home" },
  { civilian: "Bed", undercover: "Sofa", category: "Home" },
  { civilian: "Pillow", undercover: "Cushion", category: "Home" },
  { civilian: "Blanket", undercover: "Sheet", category: "Home" },
  { civilian: "Door", undercover: "Window", category: "Home" },
  { civilian: "Lock", undercover: "Key", category: "Home" },
  { civilian: "Switch", undercover: "Plug", category: "Home" },
  { civilian: "Wire", undercover: "Rope", category: "Home" },
  { civilian: "Tap", undercover: "Shower", category: "Home" },
  { civilian: "Toothbrush", undercover: "Toothpaste", category: "Home" },
  { civilian: "Comb", undercover: "Brush", category: "Home" },
  { civilian: "Mirror", undercover: "Glass", category: "Home" },
  { civilian: "Table", undercover: "Chair", category: "Home" },
  { civilian: "Plate", undercover: "Bowl", category: "Home" },
  { civilian: "Spoon", undercover: "Fork", category: "Home" },
  { civilian: "Cup", undercover: "Glass", category: "Home" },
  { civilian: "Bottle", undercover: "Jug", category: "Home" },
  { civilian: "Knife", undercover: "Scissors", category: "Home" },
  { civilian: "Gas Stove", undercover: "Induction", category: "Home" },
  { civilian: "Fridge", undercover: "Oven", category: "Home" },
  { civilian: "Matchbox", undercover: "Lighter", category: "Home" },
  { civilian: "Candle", undercover: "Diya", category: "Home" },
  { civilian: "Agarbatti", undercover: "Perfume", category: "Home" },
  { civilian: "Umbrella", undercover: "Raincoat", category: "Home" },
  { civilian: "Bag", undercover: "Purse", category: "Home" },
  { civilian: "Wallet", undercover: "Pocket", category: "Home" },
  { civilian: "Pen", undercover: "Pencil", category: "Home" },
  { civilian: "Paper", undercover: "Notebook", category: "Home" },
  { civilian: "Book", undercover: "Newspaper", category: "Home" },
  { civilian: "Phone", undercover: "Tablet", category: "Home" },
  { civilian: "Laptop", undercover: "Computer", category: "Home" },
  { civilian: "Charger", undercover: "Powerbank", category: "Home" },
  { civilian: "Sim Card", undercover: "Memory Card", category: "Home" },
  { civilian: "Headphone", undercover: "Earphone", category: "Home" },
  { civilian: "TV", undercover: "Remote", category: "Home" },
  { civilian: "Clock", undercover: "Watch", category: "Home" },
  { civilian: "Calendar", undercover: "Diary", category: "Home" },
  { civilian: "Dustbin", undercover: "Bag", category: "Home" },
  { civilian: "Slipper", undercover: "Shoe", category: "Home" },
  { civilian: "Sock", undercover: "Glove", category: "Home" },
  { civilian: "Shirt", undercover: "T-Shirt", category: "Home" },
  { civilian: "Pant", undercover: "Jeans", category: "Home" },
  { civilian: "Kurta", undercover: "Sherwani", category: "Home" },
  { civilian: "Sari", undercover: "Dupatta", category: "Home" },
  { civilian: "Ring", undercover: "Bangle", category: "Home" },
  { civilian: "Gold", undercover: "Silver", category: "Home" },

  // --- TRANSPORT & TRAVEL ---
  { civilian: "Auto Rickshaw", undercover: "Taxi", category: "Travel" },
  { civilian: "Train", undercover: "Metro", category: "Travel" },
  { civilian: "Bus", undercover: "Truck", category: "Travel" },
  { civilian: "Scooter", undercover: "Bike", category: "Travel" },
  { civilian: "Car", undercover: "Jeep", category: "Travel" },
  { civilian: "Cycle", undercover: "Bike", category: "Travel" },
  { civilian: "Plane", undercover: "Helicopter", category: "Travel" },
  { civilian: "Road", undercover: "Highway", category: "Travel" },
  { civilian: "Bridge", undercover: "Flyover", category: "Travel" },
  { civilian: "Ticket", undercover: "Pass", category: "Travel" },
  { civilian: "Driver", undercover: "Conductor", category: "Travel" },
  { civilian: "Traffic", undercover: "Signal", category: "Travel" },
  { civilian: "Petrol", undercover: "Diesel", category: "Travel" },
  { civilian: "Wheel", undercover: "Tyre", category: "Travel" },
  { civilian: "Seat", undercover: "Berth", category: "Travel" },
  { civilian: "Station", undercover: "Airport", category: "Travel" },
  { civilian: "Hotel", undercover: "Lodge", category: "Travel" },
  { civilian: "Map", undercover: "GPS", category: "Travel" },
  { civilian: "Luggage", undercover: "Backpack", category: "Travel" },
  { civilian: "Passport", undercover: "Visa", category: "Travel" },

  // --- CRICKET, MOVIES & FUN ---
  { civilian: "Cricket", undercover: "Hockey", category: "Fun" },
  { civilian: "Bat", undercover: "Ball", category: "Fun" },
  { civilian: "Wicket", undercover: "Stump", category: "Fun" },
  { civilian: "Bowler", undercover: "Batsman", category: "Fun" },
  { civilian: "Six", undercover: "Four", category: "Fun" },
  { civilian: "Umpire", undercover: "Referee", category: "Fun" },
  { civilian: "Stadium", undercover: "Ground", category: "Fun" },
  { civilian: "IPL", undercover: "World Cup", category: "Fun" },
  { civilian: "Football", undercover: "Volleyball", category: "Fun" },
  { civilian: "Ludo", undercover: "Carrom", category: "Fun" },
  { civilian: "Cards", undercover: "Chess", category: "Fun" },
  { civilian: "Pubg", undercover: "Free Fire", category: "Fun" },
  { civilian: "Movie", undercover: "Serial", category: "Fun" },
  { civilian: "Hero", undercover: "Villain", category: "Fun" },
  { civilian: "Song", undercover: "Dance", category: "Fun" },
  { civilian: "Cinema", undercover: "Netflix", category: "Fun" },
  { civilian: "Comedy", undercover: "Action", category: "Fun" },
  { civilian: "Horror", undercover: "Thriller", category: "Fun" },
  { civilian: "Magic", undercover: "Circus", category: "Fun" },
  { civilian: "Park", undercover: "Garden", category: "Fun" },
  { civilian: "Picnic", undercover: "Party", category: "Fun" },
  { civilian: "Wedding", undercover: "Reception", category: "Fun" },
  { civilian: "Birthday", undercover: "Anniversary", category: "Fun" },
  { civilian: "Gift", undercover: "Cake", category: "Fun" },
  { civilian: "Diwali", undercover: "Holi", category: "Fun" },
  { civilian: "Eid", undercover: "Christmas", category: "Fun" },
  { civilian: "Rakhi", undercover: "Gift", category: "Fun" },
  { civilian: "Kite", undercover: "Balloon", category: "Fun" },
  { civilian: "Selfie", undercover: "Photo", category: "Fun" },
  { civilian: "Instagram", undercover: "WhatsApp", category: "Fun" },

  // --- NATURE & ANIMALS ---
  { civilian: "Dog", undercover: "Cat", category: "Nature" },
  { civilian: "Cow", undercover: "Buffalo", category: "Nature" },
  { civilian: "Goat", undercover: "Sheep", category: "Nature" },
  { civilian: "Horse", undercover: "Donkey", category: "Nature" },
  { civilian: "Monkey", undercover: "Langur", category: "Nature" },
  { civilian: "Tiger", undercover: "Lion", category: "Nature" },
  { civilian: "Elephant", undercover: "Camel", category: "Nature" },
  { civilian: "Snake", undercover: "Lizard", category: "Nature" },
  { civilian: "Rat", undercover: "Mouse", category: "Nature" },
  { civilian: "Mosquito", undercover: "Fly", category: "Nature" },
  { civilian: "Ant", undercover: "Spider", category: "Nature" },
  { civilian: "Bird", undercover: "Crow", category: "Nature" },
  { civilian: "Parrot", undercover: "Peacock", category: "Nature" },
  { civilian: "Eagle", undercover: "Kite", category: "Nature" },
  { civilian: "Chicken", undercover: "Duck", category: "Nature" },
  { civilian: "Fish", undercover: "Frog", category: "Nature" },
  { civilian: "Tree", undercover: "Plant", category: "Nature" },
  { civilian: "Flower", undercover: "Leaf", category: "Nature" },
  { civilian: "Rose", undercover: "Lotus", category: "Nature" },
  { civilian: "Grass", undercover: "Ground", category: "Nature" },
  { civilian: "Sun", undercover: "Moon", category: "Nature" },
  { civilian: "Star", undercover: "Sky", category: "Nature" },
  { civilian: "Cloud", undercover: "Rain", category: "Nature" },
  { civilian: "Wind", undercover: "Storm", category: "Nature" },
  { civilian: "River", undercover: "Sea", category: "Nature" },
  { civilian: "Mountain", undercover: "Hill", category: "Nature" },
  { civilian: "Forest", undercover: "Jungle", category: "Nature" },
  { civilian: "Mud", undercover: "Sand", category: "Nature" },
  { civilian: "Fire", undercover: "Smoke", category: "Nature" },
  { civilian: "Summer", undercover: "Winter", category: "Nature" },

  // --- SCHOOL & JOBS ---
  { civilian: "School", undercover: "College", category: "School" },
  { civilian: "Teacher", undercover: "Student", category: "School" },
  { civilian: "Exam", undercover: "Test", category: "School" },
  { civilian: "Pen", undercover: "Pencil", category: "School" },
  { civilian: "Bag", undercover: "Book", category: "School" },
  { civilian: "Class", undercover: "Tuition", category: "School" },
  { civilian: "Homework", undercover: "Project", category: "School" },
  { civilian: "Lunch", undercover: "Recess", category: "School" },
  { civilian: "Uniform", undercover: "Dress", category: "School" },
  { civilian: "Result", undercover: "Marks", category: "School" },
  { civilian: "Doctor", undercover: "Nurse", category: "Jobs" },
  { civilian: "Police", undercover: "Soldier", category: "Jobs" },
  { civilian: "Thief", undercover: "Robber", category: "Jobs" },
  { civilian: "Shopkeeper", undercover: "Customer", category: "Jobs" },
  { civilian: "Farmer", undercover: "Gardener", category: "Jobs" },
  { civilian: "Driver", undercover: "Mechanic", category: "Jobs" },
  { civilian: "Cook", undercover: "Waiter", category: "Jobs" },
  { civilian: "Boss", undercover: "Manager", category: "Jobs" },
  { civilian: "Actor", undercover: "Singer", category: "Jobs" },
  { civilian: "Pilot", undercover: "Captain", category: "Jobs" },
  { civilian: "Judge", undercover: "Lawyer", category: "Jobs" },
  { civilian: "Scientist", undercover: "Engineer", category: "Jobs" },

  // --- BODY & PEOPLE ---
  { civilian: "Hand", undercover: "Leg", category: "Body" },
  { civilian: "Finger", undercover: "Thumb", category: "Body" },
  { civilian: "Eye", undercover: "Ear", category: "Body" },
  { civilian: "Nose", undercover: "Mouth", category: "Body" },
  { civilian: "Hair", undercover: "Head", category: "Body" },
  { civilian: "Teeth", undercover: "Tongue", category: "Body" },
  { civilian: "Stomach", undercover: "Back", category: "Body" },
  { civilian: "Heart", undercover: "Brain", category: "Body" },
  { civilian: "Bone", undercover: "Muscle", category: "Body" },
  { civilian: "Blood", undercover: "Sweat", category: "Body" },
  { civilian: "Man", undercover: "Boy", category: "People" },
  { civilian: "Woman", undercover: "Girl", category: "People" },
  { civilian: "Baby", undercover: "Child", category: "People" },
  { civilian: "Mom", undercover: "Dad", category: "People" },
  { civilian: "Brother", undercover: "Sister", category: "People" },
  { civilian: "Grandma", undercover: "Grandpa", category: "People" },
  { civilian: "Friend", undercover: "Neighbor", category: "People" },
  { civilian: "Guest", undercover: "Relative", category: "People" },
  { civilian: "King", undercover: "Queen", category: "People" },
  { civilian: "Rich", undercover: "Poor", category: "People" },

  // --- OPPOSITES & ABSTRACT ---
  { civilian: "Happy", undercover: "Sad", category: "Abstract" },
  { civilian: "Good", undercover: "Bad", category: "Abstract" },
  { civilian: "Hot", undercover: "Cold", category: "Abstract" },
  { civilian: "Big", undercover: "Small", category: "Abstract" },
  { civilian: "Fast", undercover: "Slow", category: "Abstract" },
  { civilian: "Up", undercover: "Down", category: "Abstract" },
  { civilian: "Left", undercover: "Right", category: "Abstract" },
  { civilian: "Day", undercover: "Night", category: "Abstract" },
  { civilian: "Light", undercover: "Dark", category: "Abstract" },
  { civilian: "Hard", undercover: "Soft", category: "Abstract" },
  { civilian: "New", undercover: "Old", category: "Abstract" },
  { civilian: "Clean", undercover: "Dirty", category: "Abstract" },
  { civilian: "Love", undercover: "Hate", category: "Abstract" },
  { civilian: "Truth", undercover: "Lie", category: "Abstract" },
  { civilian: "Win", undercover: "Lose", category: "Abstract" },
  { civilian: "Start", undercover: "Stop", category: "Abstract" },
  { civilian: "Open", undercover: "Close", category: "Abstract" },
  { civilian: "In", undercover: "Out", category: "Abstract" },
  { civilian: "Buy", undercover: "Sell", category: "Abstract" },
  { civilian: "Give", undercover: "Take", category: "Abstract" },
  { civilian: "Push", undercover: "Pull", category: "Abstract" },
  { civilian: "Sit", undercover: "Stand", category: "Abstract" },
  { civilian: "Sleep", undercover: "Wake", category: "Abstract" },
  { civilian: "Eat", undercover: "Drink", category: "Abstract" },
  { civilian: "Laugh", undercover: "Cry", category: "Abstract" },
  { civilian: "Run", undercover: "Walk", category: "Abstract" },
  { civilian: "Talk", undercover: "Sing", category: "Abstract" },
  { civilian: "Read", undercover: "Write", category: "Abstract" },
  { civilian: "Question", undercover: "Answer", category: "Abstract" },
  { civilian: "Problem", undercover: "Solution", category: "Abstract" },

  // --- PLACES (Simple) ---
  { civilian: "Village", undercover: "City", category: "Places" },
  { civilian: "Shop", undercover: "Mall", category: "Places" },
  { civilian: "Park", undercover: "Zoo", category: "Places" },
  { civilian: "Hospital", undercover: "Clinic", category: "Places" },
  { civilian: "Bank", undercover: "ATM", category: "Places" },
  { civilian: "Temple", undercover: "Mosque", category: "Places" },
  { civilian: "Gym", undercover: "Playground", category: "Places" },
  { civilian: "Office", undercover: "Factory", category: "Places" },
  { civilian: "Kitchen", undercover: "Hall", category: "Places" },
  { civilian: "Bathroom", undercover: "Toilet", category: "Places" },
  { civilian: "Roof", undercover: "Balcony", category: "Places" },
  { civilian: "Market", undercover: "Fair (Mela)", category: "Places" },
  { civilian: "India", undercover: "China", category: "Places" },
  { civilian: "Mumbai", undercover: "Delhi", category: "Places" },
  { civilian: "Goa", undercover: "Kerala", category: "Places" },
  { civilian: "Road", undercover: "Street", category: "Places" },
  { civilian: "Farm", undercover: "Garden", category: "Places" },
  { civilian: "Jungle", undercover: "Forest", category: "Places" },
  { civilian: "River", undercover: "Lake", category: "Places" },
  { civilian: "Beach", undercover: "Island", category: "Places" },

  // --- COLORS & SHAPES ---
  { civilian: "Red", undercover: "Pink", category: "Colors" },
  { civilian: "Blue", undercover: "Green", category: "Colors" },
  { civilian: "Black", undercover: "White", category: "Colors" },
  { civilian: "Yellow", undercover: "Orange", category: "Colors" },
  { civilian: "Gold", undercover: "Silver", category: "Colors" },
  { civilian: "Circle", undercover: "Oval", category: "Shapes" },
  { civilian: "Square", undercover: "Rectangle", category: "Shapes" },
  { civilian: "Triangle", undercover: "Star", category: "Shapes" },
  { civilian: "Line", undercover: "Dot", category: "Shapes" },
  { civilian: "Box", undercover: "Cube", category: "Shapes" }
]

export const getRandomWordPair = ({ categories = [] }) => {
  let eligibleWords = wordPairs
  if (categories.length > 0) {
    eligibleWords = wordPairs.filter(pair => categories.includes(pair.category))
  }

  if (eligibleWords.length === 0) {
    eligibleWords = wordPairs
  }

  const randomIndex = Math.floor(Math.random() * eligibleWords.length)
  return eligibleWords[randomIndex]
}
